version: '3.8'
services:
# nginx ------------------------------------------------------------
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html/
    restart: unless-stopped
    networks:
      inception:

# wordpress ------------------------------------------------------------
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      inception:

# mariadb ------------------------------------------------------------
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      inception:

networks:
  inception:
    name: inception-network
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb
    driver: local
    driver_opts:
      type: bind
      device: /home/$(USER)/data/mariadb
      o: bind

  wordpress_data:
    name: wordpress
    driver: local
    driver_opts:
      type: bind
      device: /home/$(USER)/data/wordpress
      o: bind
